services:

  # Each user has their own container, so they can run their own code without interfering with each other.

  gmfi-1:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ${COMPOSE_PROJECT_NAME}_${USER_1}

    restart: unless-stopped

    ports:
      - "${TAILSCALE_IP}:${PORT_1}:8050"

    env_file:
      - .env

    environment:
      GMFI_USER=${USER_1}

    volumes:
      - ./data_${USER_1}:/app/data
      - ./configuration:/app/configuration

    gmfi-2:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ${COMPOSE_PROJECT_NAME}_${USER_2}

    restart: unless-stopped

    ports:
      - "${TAILSCALE_IP}:${PORT_2}:8050"

    env_file:
      - .env

    environment:
      GMFI_USER=${USER_2}

    volumes:
      - ./data_${USER_2}:/app/data
      - ./configuration:/app/configuration
