services:
  gmfi:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ${COMPOSE_PROJECT_NAME}

    restart: unless-stopped

    ports:
      - "${TAILSCALE_IP}:${PORT}:${PORT}"

    env_file:
      - .env

    volumes:
      - ./data:/app/data