services:

  # Each user has their own container, so they can run their own code without interfering with each other.

  gmfi-1:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ${COMPOSE_PROJECT_NAME}_${USER_1}

    restart: unless-stopped

    ports:
      - "${TAILSCALE_IP}:${PORT_1}:${PORT_1}"

    env_file:
      - .env

    volumes:
      - ./data_1:/app/data

  gmfi-2:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ${COMPOSE_PROJECT_NAME}_${USER_2}

    restart: unless-stopped

    ports:
      - "${TAILSCALE_IP}:${PORT_2}:${PORT_2}"

    env_file:
      - .env

    volumes:
      - ./data_2:/app/data